apps/accounts/api/urls.py
from django.conf.urls.defaults import *
from piston.resource import Resource
from piston.emitters import Emitter, JSONEmitter, XMLEmitter
from apps.accounts.api.handlers import AccountHandler

account_handler = Resource(AccountHandler)
Emitter.register('.json', JSONEmitter, 'application/json; charset=utf-8')
Emitter.register('.json/', JSONEmitter, 'application/json; charset=utf-8')
Emitter.register('.xml', XMLEmitter, 'text/xml; charset=utf-8')
Emitter.register('.xml/', XMLEmitter, 'text/xml; charset=utf-8')

urlpatterns = patterns('',
	url(r'^(?P<emitter_format>[\.a-z]+)$', account_handler, {
		'SSL': True,
	}, name='api-account'),
)

apps/accounts/urls.py
from django.conf.urls.defaults import *
from apps.accounts import views

urlpatterns = patterns('',
	url(r'^$', views.profile, {'SSL': True}, name='accounts_profile'),
	url(r'^login/$', views.login, name='accounts_login'),
	url(r'^logout/$', views.logout, name='accounts_logout'),
	url(r'^register/$', views.register, name='accounts_register'),
	url(r'^created/$', views.register, name='accounts_created'),
	url(r'^reset/$', views.reset, {'SSL': True}, name='accounts_reset'),
	url(r'^resetconfirmation/(?P<reset_key>.+)$', views.resetconfirmation, {'SSL': True}, name='accounts_resetconfirmation'),
	url(r'^activate/(?P<activation_key>.+)$', views.activate, name='accounts_activate'),
	
	url(r'^admin/refreshqualityoflife/$', views.refresh_quality_of_life, {'SSL': True}, name='refresh_quality_of_life'),
	
	#url(r'^(?P<user_id>\d+)$', views.profile, name='accounts_profile'),
	url(r'^(?P<username>[^/]+)$', views.profile, name='accounts_profile'),
	
)

apps/django-piston/examples/blogserver/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('blogserver.blog.urls')),
    (r'^api/', include('blogserver.api.urls')),
    (r'^admin/(.*)', admin.site.root),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	
	# Home
	#url(r'^$', direct_to_template, {
	#	"template": "homepage.html",
	#}, name="home"),
	
	# Errors
	url(r'^error/404$', direct_to_template, {
		"template": "404.html",
	}, name="404"),
	url(r'^error/500$', direct_to_template, {
		"template": "500.html",
	}, name="500"),
	
	# API
	(r'^api/accounts', include('apps.accounts.api.urls')),
	(r'^api/records', include('apps.records.api.urls')),
	(r'^api/tags', include('apps.tags.api.urls')),
	(r'^api/stats', include('apps.stats.api.urls')),
	(r'^api/suggestions', include('apps.suggestions.api.urls')),
	
	# Normal
	(r'^', include('apps.about.urls')),
	(r'^accounts/', include('apps.accounts.urls')),
	(r'^records/', include('apps.records.urls')),
	(r'^tags/', include('apps.tags.urls')),
	(r'^leaderboards/', include('apps.leaderboards.urls')),
	#(r'^stats/', include('apps.stats.urls')),
	(r'^suggestions/', include('apps.suggestions.urls')),
	
	# Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
	# to INSTALLED_APPS to enable admin documentation:
	# (r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	(r'^admin/', include(admin.site.urls)),
)

if settings.SERVE_MEDIA:
	urlpatterns += patterns('',
		(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
			{'document_root': settings.MEDIA_ROOT}),
	)

apps/accounts/models.py
import datetime
import random
import re

from apps.records.models import Record

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db import transaction
from django.template.loader import render_to_string
from django.utils.hashcompat import sha_constructor
from django.utils.translation import ugettext_lazy as _


SHA1_RE = re.compile('^[a-f0-9]{40}$')


class RegistrationManager(models.Manager):
	"""
	Custom manager for the ``RegistrationProfile`` model.
	
	The methods defined here provide shortcuts for account creation
	and activation (including generation and emailing of activation
	keys), and for cleaning out expired inactive accounts.
	
	"""
	def activate_user(self, activation_key):
		"""
		Validate an activation key and activate the corresponding
		``User`` if valid.
		
		If the key is valid and has not expired, return the ``User``
		after activating.
		
		If the key is not valid or has expired, return ``False``.
		
		If the key is valid but the ``User`` is already active,
		return ``False``.
		
		To prevent reactivation of an account which has been
		deactivated by site administrators, the activation key is
		reset to the string constant ``RegistrationProfile.ACTIVATED``
		after successful activation.

		"""
		# Make sure the key we're trying conforms to the pattern of a
		# SHA1 hash; if it doesn't, no point trying to look it up in
		# the database.
		if SHA1_RE.search(activation_key):
			try:
				profile = self.get(activation_key=activation_key)
			except self.model.DoesNotExist:
				return False
			if not profile.activation_key_expired():
				user = profile.user
				user.is_active = True
				user.save()
				profile.activation_key = self.model.ACTIVATED
				profile.save()
				return user
		return False
	
	def disable_reset_key(self, reset_key):
		
		try:
			profile = self.get(reset_key=reset_key)
		except self.model.DoesNotExist:
			return False
		
		if profile:
			profile.reset_key = self.model.DISABLED_RESET_KEY
			profile.save()
			return profile
		
		return False
	
	def create_inactive_user(self, username, email, password,
							 site, send_email=True):
		"""
		Create a new, inactive ``User``, generate a
		``RegistrationProfile`` and email its activation key to the
		``User``, returning the new ``User``.

		By default, an activation email will be sent to the new
		user. To disable this, pass ``send_email=False``.
		
		"""
		new_user = User.objects.create_user(username, email, password)
		new_user.is_active = False
		new_user.save()

		registration_profile = self.create_profile(new_user)

		if send_email:
			registration_profile.send_activation_email(site)

		return new_user
	create_inactive_user = transaction.commit_on_success(create_inactive_user)

	def create_profile(self, user):
		"""
		Create a ``RegistrationProfile`` for a given
		``User``, and return the ``RegistrationProfile``.
		
		The activation key for the ``RegistrationProfile`` will be a
		SHA1 hash, generated from a combination of the ``User``'s
		username and a random salt.
		
		"""
		
		salt = sha_constructor(str(random.random())).hexdigest()[:5]
		activation_key = sha_constructor(salt+user.username).hexdigest()
		
		# I don't know why this stopped working...
		#return self.create(user=user, activation_key=activation_key)
		
		return RegistrationProfile(user=user, activation_key=activation_key)
	
	def delete_expired_users(self):
		"""
		Remove expired instances of ``RegistrationProfile`` and their
		associated ``User``s.
		
		Accounts to be deleted are identified by searching for
		instances of ``RegistrationProfile`` with expired activation
		keys, and then checking to see if their associated ``User``
		instances have the field ``is_active`` set to ``False``; any
		``User`` who is both inactive and has an expired activation
		key will be deleted.
		
		It is recommended that this method be executed regularly as
		part of your routine site maintenance; this application
		provides a custom management command which will call this
		method, accessible as ``manage.py cleanupregistration``.
		
		Regularly clearing out accounts which have never been
		activated serves two useful purposes:
		
		1. It alleviates the ocasional need to reset a
		   ``RegistrationProfile`` and/or re-send an activation email
		   when a user does not receive or does not act upon the
		   initial activation email; since the account will be
		   deleted, the user will be able to simply re-register and
		   receive a new activation key.
		
		2. It prevents the possibility of a malicious user registering
		   one or more accounts and never activating them (thus
		   denying the use of those usernames to anyone else); since
		   those accounts will be deleted, the usernames will become
		   available for use again.
		
		If you have a troublesome ``User`` and wish to disable their
		account while keeping it in the database, simply delete the
		associated ``RegistrationProfile``; an inactive ``User`` which
		does not have an associated ``RegistrationProfile`` will not
		be deleted.
		
		"""
		for profile in self.all():
			if profile.activation_key_expired():
				user = profile.user
				if not user.is_active:
					user.delete()


class RegistrationProfile(models.Model):
	"""
	A simple profile which stores an activation key for use during
	user account registration.
	
	Generally, you will not want to interact directly with instances
	of this model; the provided manager includes methods
	for creating and activating new accounts, as well as for cleaning
	out accounts which have never been activated.
	
	While it is possible to use this model as the value of the
	``AUTH_PROFILE_MODULE`` setting, it's not recommended that you do
	so. This model's sole purpose is to store data temporarily during
	account registration and activation.
	
	"""
	ACTIVATED = u"ALREADY_ACTIVATED"
	DISABLED_RESET_KEY = u"DISABLED"
	
	user = models.ForeignKey(User, unique=True, verbose_name=_('user'))
	activation_key = models.CharField(_('activation key'), max_length=40)
	reset_key = models.CharField(_('reset key'), max_length=40)
	reset_key_created = models.DateTimeField(default=datetime.datetime.now())
	facebook_id = models.BigIntegerField(null=True)
	quality_of_life = models.FloatField(null=True, max_length=6)
	last_viewed_friends_shared = models.DateTimeField(default=datetime.datetime.now())
	
	objects = RegistrationManager()
	
	class Meta:
		verbose_name = _('registration profile')
		verbose_name_plural = _('registration profiles')
	
	def __unicode__(self):
		return u"Registration information for %s" % self.user
	
	def get_quality_of_life(self):
		
		# init
		records = False
		total_quality = 0
		num_records_with_value = 0
		average = None
		
		# get all user records
		records = Record.objects.all().filter(user=self.user)
		
		# go through all the records and add up the total record quality
		for record in records:
			if record.quality >= 0:
				total_quality = total_quality + record.quality
				num_records_with_value += 1
		
		# get the average (aka: quality)
		if num_records_with_value > 0:
			average = total_quality / num_records_with_value
		
		return average
	
	def activation_key_expired(self):
		"""
		Determine whether this ``RegistrationProfile``'s activation
		key has expired, returning a boolean -- ``True`` if the key
		has expired.
		
		Key expiration is determined by a two-step process:
		
		1. If the user has already activated, the key will have been
		   reset to the string constant ``ACTIVATED``. Re-activating
		   is not permitted, and so this method returns ``True`` in
		   this case.

		2. Otherwise, the date the user signed up is incremented by
		   the number of days specified in the setting
		   ``ACCOUNT_ACTIVATION_DAYS`` (which should be the number of
		   days after signup during which a user is allowed to
		   activate their account); if the result is less than or
		   equal to the current date, the key has expired and this
		   method returns ``True``.
		
		"""
		expiration_date = datetime.timedelta(days=settings.ACCOUNT_ACTIVATION_DAYS)
		return self.activation_key == self.ACTIVATED or \
			   (self.user.date_joined + expiration_date <= datetime.datetime.now())
	activation_key_expired.boolean = True
	
	def reset_key_expired(self):
		
		# key has expired
		if self.reset_key_created+datetime.timedelta(days=settings.ACCOUNT_ACTIVATION_DAYS) < datetime.datetime.now():
			return True
		
		# key has already been used
		if self.reset_key == self.DISABLED_RESET_KEY:
			return True
		
		return False
	reset_key_expired.boolean = False
	
	def generate_reset_key(self, user):
		salt = sha_constructor(str(random.random())).hexdigest()[:5]
		self.reset_key = sha_constructor(salt+user.username).hexdigest()
		self.reset_key_created = datetime.datetime.now()
		
		self.save()
		
		return self
	
	def send_activation_email(self, site):
		"""
		Send an activation email to the user associated with this
		``RegistrationProfile``.
		
		The activation email will make use of two templates:

		``registration/activation_email_subject.txt``
			This template will be used for the subject line of the
			email. Because it is used as the subject line of an email,
			this template's output **must** be only a single line of
			text; output longer than one line will be forcibly joined
			into only a single line.

		``registration/activation_email.txt``
			This template will be used for the body of the email.

		These templates will each receive the following context
		variables:

		``activation_key``
			The activation key for the new account.

		``expiration_days``
			The number of days remaining during which the account may
			be activated.

		``site``
			An object representing the site on which the user
			registered; depending on whether ``django.contrib.sites``
			is installed, this may be an instance of either
			``django.contrib.sites.models.Site`` (if the sites
			application is installed) or

apps/tags/forms.py
from django.db import models
from django import forms
import settings

from tagging.models import Tag
from tagging.forms import TagField
from django.utils.translation import ugettext_lazy as _

class TagForm(forms.ModelForm):
	name = forms.RegexField(label=_('Name'), regex=r'^[\'\w\-\!\@\#\$\%\^\&\*\(\),\s\.]+$', max_length=settings.MAX_TAG_LENGTH)
	
	def clean_name(self):
		name = str(self.cleaned_data['name'])
		
		# all tags should be lowercase
		if settings.FORCE_LOWERCASE_TAGS:
			name = name.lower()
		
		return name
	
	class Meta:
		model = Tag
		exclude = ('value', 'facebook_name', 'facebook_id')

templates/accounts/base.html
{% extends "base.html" %}

templates/accounts/login.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Login" %}{% endblock %}
{% block body_class %}login{% endblock %}

{% block sidebar %}
	<ul id="site_sidebar">
		<li class="sidebar_item">
			<h3>{% trans "No account?" %}</h3>
			<a href="{% url accounts_register %}" class="input_button_wrapper">
				<div class="input_button_start"></div>
				<div class="input_button_body">
					<div class="icon icon_register"></div>
					<span>{% trans "Register Now" %}</span>
				</div>
				<div class="input_button_end"></div>
			</a>
		</li>
	</ul>
{% endblock sidebar %}

{% block body %}
	
	<h2>{% trans "Login to your account" %}</h2>
	<p>{% trans "You'll have your life indexed before you know it." %}</p>
	
	{% if form.has_errors %}
		<p class="error">{% trans "Sorry, that's not a valid username or password" %}</p>
	{% endif %}
	
	<form class="record_form use_inline_labels" action='.' method='post'>{% csrf_token %}
		<fieldset>
			<div id="id_username_field" class="field">
				<label for="username">{% trans "Your Username" %}</label>
				<input type="text" name="username" value="" id="username">
			</div>
			<div id="id_password_field" class="field">
				<label for="password">{% trans "Your Password" %}</label>
				<input type="password" name="password" value="" id="password">
			</div>
		</fieldset>
		
		<div class="actions">
			<div class="actions_right">
				<div class="input_button_wrapper">
					<div class="input_button_start"></div>
					<div class="input_button_body">
						<div class="icon icon_login"></div>
						<input type="submit" id="account_login" name="submit" value="{% trans "Login" %}" class="input_submit" />
					</div>
					<div class="input_button_end"></div>
				</div>
			</div>
		</div>
	</form>
	
{% endblock %}

templates/accounts/profile.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Profile" %}{% endblock %}
{% block body_class %}profile{% endblock %}

{% block body %}
	<div class="site_content_tabs use_tabs">
		<ul class="tabs">
			<li class="active"><a href="#profile">{% trans "Profile" %}</a></li>
			<li class=""><a href="#stats">{% trans "Stats" %}</a></li>
			<li class=""><a href="#achievements">{% trans "Achievements" %}</a></li>
		</ul>
		
		<div class="tab_container">
			<div id="profile" class="tab_content">
				<div class="form_items_container">
					<ul class="form_items">
						<li>
							<div class="container">
								<div class="header">
									<div class="label">
										<label class="icon icon_name" for="id_name">{% trans "Name" %}</label>
									</div>
									<div id="id_name" class="content">
										{{ viewed_user.get_full_name }}
									</div>
								</div>
							</div>
						</li>
						{% if has_real_userame %}
							<li>
								<div class="container">
									<div class="header">
										<div class="label">
											<label class="icon icon_username" for="id_username">{% trans "Username" %}</label>
										</div>
										<div id="id_username" class="content">
											{{ viewed_user.username }}
										</div>
									</div>
								</div>
							</li>
						{% endif %}
						<li>
							<div class="container">
								<div class="header">
									<div class="label">
										<label class="icon icon_email" for="id_email">{% trans "Email" %}</label>
									</div>
									<div id="id_email" class="content">
										{{ viewed_user.email }}
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="container">
								<div class="header">
									<div class="label">
										<label class="icon icon_password" for="id_password">{% trans "Password" %}</label>
									</div>
									<div id="id_password" class="content">
										&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="container">
								<div class="header">
									<div class="label">
										<label class="icon icon_date_joined" for="id_date_joined">{% trans "Joined" %}</label>
									</div>
									<div id="id_date_joined" class="content">
										{{ viewed_user.date_joined|date:"F d, Y" }} at {{ viewed_user.date_joined|date:"g:iA" }}
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="container">
								<div class="header">
									<div class="label">
										<label class="icon icon_quality_of_life" for="id_quality_of_life">{% trans "Quality of Life" %}</label>
									</div>
									<div id="id_quality_of_life" class="content">
										{% if viewed_user_registration_profile.quality_of_life %}
											{{ viewed_user_registration_profile.quality_of_life|floatformat:1 }}%
										{% else %}
											{% trans "N/A" %}
										{% endif %}
									</div>
								</div>
							</div>
						</li>
					</ul>
				</div>
			</div>
			
			<div id="stats" class="tab_content hidden">
				<div class="tab_menu">
					<div class="menu_large use_tab_menu use_stats_menu">
						<ul class="menu_headers">
							<li class="menu_header">
								<div class="menu_header_icon icon icon_stats"></div>
								<div class="menu_header_text">{% trans "Other Stats" %}</div>
								<div class="side"></div>
							</li>
						</ul>
						<ul class="menu_items">
							<li class="menu_item">
								<span class="menu_item_icon icon icon_quality_of_life"></span>
								<span class="menu_item_text">{% trans "Quality of Life" %}</span>
								<span class="menu_item_desc">{% trans "by Weekday" %}</span>
								<span class="menu_item_value">weekly</span>
							</li>
							<li class="menu_item">
								<span class="menu_item_icon icon"></span>
								<span class="menu_item_desc">{% trans "by Month" %}</span>
								<span class="menu_item_value">monthly</span>
							</li>
							<li class="menu_item">
								<span class="menu_item_icon icon"></span>
								<span class="menu_item_desc">{% trans "by Year" %}</span>
								<span class="menu_item_value">yearly</span>
							</li>
							<li class="menu_item">
								<span class="menu_item_icon icon icon_records"></span>
								<span class="menu_item_text">{% trans "Records" %}</span>
								<span class="menu_item_desc">{% trans "General stats about your records." %}</span>
								<span class="menu_item_value">record_counts</span>
							</li>
							<li class="menu_item">
								<span class="menu_item_icon icon icon_tags"></span>
								<span class="menu_item_text">{% trans "Tags" %}</span>
								<span class="menu_item_desc">{% trans "General stats about your tags." %}</span>
								<span class="menu_item_value">tag_counts</span>
							</li>
							<li class="menu_item">
								<span class="menu_item_icon icon"></span>
								<span class="menu_item_desc">{% trans "Top Used" %}</span>
								<span class="menu_item_value">top_tags</span>
							</li>
						</ul>
					</div>
				</div>
				
				<div class="form_items_container">
					<div id="stats_container">
						
						<div class="loading"></div>
						
					</div>
				</div>
			</div>
			
			<div id="achievements" class="tab_content hidden">
				<div class="important_message">
					<h3>Achievements are Coming Soon</h3>
					<h4>We're currently developing this truely awesome feature, so stay tuned!</h4>
				</div>
			</div>
		</div>
	</div>
	
	<div class="clear"></div>
	
	
{% endblock %}

templates/accounts/register.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Register" %}{% endblock %}
{% block body_class %}register{% endblock %}

{% block sidebar %}
	<ul id="site_sidebar">
		<li class="sidebar_item">
			<h3>{% trans "Have an account?" %}</h3>
			<a href="{% url accounts_login %}" class="input_button_wrapper">
				<div class="input_button_start"></div>
				<div class="input_button_body">
					<div class="icon icon_login"></div>
					<span>{% trans "Login" %}</span>
				</div>
				<div class="input_button_end"></div>
			</a>
		</li>
	</ul>
{% endblock sidebar %}

{% block body %}
<h2>Create your Synapsie account now</h2>
<p>You'll have your life indexed before you know it.</p>

<form class="record_form use_inline_labels" action='.' method='post'>{% csrf_token %}
	<fieldset>
		<div id="id_username_field" class="field">
			{{ formset.username.label_tag }}
			{{ formset.username }}
		</div>
		<div id="id_password1_field" class="field">
			{{ formset.password1.label_tag }}
			{{ formset.password1 }}
		</div>
		<div id="id_password2_field" class="field">
			{{ formset.password2.label_tag }}
			{{ formset.password2 }}
		</div>
	</fieldset>
	
	<div class="actions">
		<div class="actions_right">
			<div class="input_button_wrapper">
				<div class="input_button_start"></div>
				<div class="input_button_body">
					<div class="icon icon_register"></div>
					<input type="submit" id="account_register" name="submit" value="{% trans "Register" %}" class="input_submit" />
				</div>
				<div class="input_button_end"></div>
			</div>
		</div>
	</div>
</form>
{% endblock %}

templates/accounts/reset.html
{% extends "marketing.html" %}

{% load i18n %}

{% block head_title %}{% trans "Reset Password" %}{% endblock %}

{% block body %}
	<div class="default_form_container">
		<div class="default_form_block">
			<h1>{% trans "Reset Password" %}</h1>
			<h4>{% trans "Enter your login email below and we will send you an email with a link to reset your password." %}</h4>
			
			<form action="{% url accounts_reset %}" method="post" id="account_reset_form" class="default_form use_inline_labels">
				{% csrf_token %}
				<fieldset>
					<div class="field">
						{{ account_reset_formset.email.label_tag }}
						{{ account_reset_formset.email }}
						{{ account_reset_formset.email.errors }}
					</div>
				</fieldset>
				
				<div class="actions">
					<div class="action_right">
						<div class="input_button_wrapper">
							<div class="input_button_start"></div>
							<div class="input_button_body">
								<div class="icon icon_account_reset"></div>
								<input type="submit" id="account_reset" name="submit" value="{% trans "Reset Password" %}" class="input_submit" />
							</div>
							<div class="input_button_end"></div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

templates/accounts/resetconfirmation.html
{% extends "marketing.html" %}

{% load i18n %}

{% block head_title %}{% trans "Create New Password" %}{% endblock %}

{% block body %}
	<div class="default_form_container">
		<div class="default_form_block">
			<h1>{% trans "Create New Password" %}</h1>
			<h4>{% trans "Provide a new password for your account below." %}</h4>
			
			<form action="{% url accounts_resetconfirmation reset_key=reset_key %}" method="post" id="account_resetconfirmation_form" class="default_form use_inline_labels">
				{% csrf_token %}
				<fieldset>
					<div class="field">
						<div class="field_combo">
							{{ accounts_resetconfirmation_formset.password1.label_tag }}
							{{ accounts_resetconfirmation_formset.password1 }}
						</div>
						<div class="field_combo omega">
							{{ accounts_resetconfirmation_formset.password2.label_tag }}
							{{ accounts_resetconfirmation_formset.password2 }}
						</div>
						{{ accounts_resetconfirmation_formset.reset_key.errors }}
						{{ accounts_resetconfirmation_formset.password1.errors }}
						{{ accounts_resetconfirmation_formset.password2.errors }}
						
						{{ accounts_resetconfirmation_formset.reset_key }}
					</div>
				</fieldset>
				
				<div class="actions">
					<div class="action_right">
						<div class="input_button_wrapper">
							<div class="input_button_start"></div>
							<div class="input_button_body">
								<div class="icon icon_account_reset"></div>
								<input type="submit" id="account_resetconfirmation" name="submit" value="{% trans "Set Password" %}" class="input_submit" />
							</div>
							<div class="input_button_end"></div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}